### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by Seaboard191743** [Seaboard191743/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by seva-seaboard** [comment]
<ul class = "header__contacts">
<li><a href = "https://www.facebook.com/profile.php?id=100004808958030" target = "_blank">facebook</a></li>
<li><a href = "mailto:ryuwins@gmail.com">ryuwins@gmail.com</a></li>
<li><a href = "https://twitter.com/denjinryu" target = "_blank">twitter</a></li>
<li><a href = "https://www.instagram.com/sworn_ryu/" target = "_blank">instagram</a></li>
</ul>

**Comment by Seaboard191743** [comment]
Thank you!
