### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by Seaboard191743** [Seaboard191743/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by seva-seaboard** [comment]
https://www.facebook.com/profile.php?id=100004808958030
ryuwins@gmail.com
https://twitter.com/denjinryu
https://www.instagram.com/sworn_ryu/

**Comment by Seaboard191743** [comment]
Well done!
